<?php
/**
 * Theme functions and setup for MyStarter.
 */

if ( ! defined( 'MYSTARTER_VERSION' ) ) {
    define( 'MYSTARTER_VERSION', wp_get_theme()->get( 'Version' ) );
}

if ( ! defined( 'MYSTARTER_BLOCKS_CONFIG' ) ) {
    define( 'MYSTARTER_BLOCKS_CONFIG', get_theme_file_path( 'config/blocks.json' ) );
}

if ( ! function_exists( 'mystarter_get_default_blocks' ) ) {
    /**
     * Liste des blocs personnalisés disponibles par défaut.
     *
     * @return array
     */
    function mystarter_get_default_blocks(): array {
        return [
            'image',
            'image-fullwidth',
            'gallery',
            'slider',
            'text-image',
            'button-group',
            'quote',
            'call-to-action',
            'rebound',
            'news-feed',
            'hero-banner',
            'hero-split',
            'column-text',
            'timeline',
            'faq',
            'logos-grid',
            'stats',
            'testimonials',
            'pricing-table',
        ];
    }
}

if ( ! function_exists( 'mystarter_get_configured_blocks' ) ) {
    /**
     * Retourne les blocs actifs à partir du fichier de configuration généré par le script.
     *
     * @return array{available:array, active:array}
     */
    function mystarter_get_configured_blocks(): array {
        $defaults = mystarter_get_default_blocks();

        if ( ! file_exists( MYSTARTER_BLOCKS_CONFIG ) ) {
            return [
                'available' => $defaults,
                'active'    => $defaults,
            ];
        }

        $config = json_decode( (string) file_get_contents( MYSTARTER_BLOCKS_CONFIG ), true );

        if ( ! is_array( $config ) ) {
            return [
                'available' => $defaults,
                'active'    => $defaults,
            ];
        }

        $available = array_values(
            array_intersect(
                $config['available'] ?? [],
                $defaults
            )
        );

        if ( empty( $available ) ) {
            $available = $defaults;
        }

        $active = array_values(
            array_intersect(
                $config['active'] ?? $available,
                $available
            )
        );

        if ( empty( $active ) ) {
            $active = $available;
        }

        return [
            'available' => array_values( array_unique( $available ) ),
            'active'    => array_values( array_unique( $active ) ),
        ];
    }
}

if ( ! function_exists( 'mystarter_setup' ) ) {
    /**
     * Configure theme defaults and support for various WordPress features.
     */
    function mystarter_setup(): void {
        load_theme_textdomain( 'mystarter', get_template_directory() . '/languages' );

        add_theme_support( 'editor-styles' );
        add_theme_support( 'wp-block-styles' );
        add_theme_support( 'align-wide' );
        add_theme_support( 'responsive-embeds' );
        add_theme_support( 'post-thumbnails' );

        add_editor_style( 'build/index.css' );
    }
}
add_action( 'after_setup_theme', 'mystarter_setup' );

/**
 * Enqueue theme stylesheet.
 */
function mystarter_enqueue_styles(): void {
    wp_enqueue_style(
        'mystarter-style',
        get_template_directory_uri() . '/style.css',
        [],
        MYSTARTER_VERSION
    );
}
add_action( 'wp_enqueue_scripts', 'mystarter_enqueue_styles' );

/**
 * Register built block assets generated by @wordpress/scripts.
 */
function mystarter_register_block_assets(): void {
    $asset_path = get_stylesheet_directory() . '/build/index.asset.php';

    if ( ! file_exists( $asset_path ) ) {
        return;
    }

    $asset = include $asset_path;

    wp_register_script(
        'mystarter-blocks',
        get_stylesheet_directory_uri() . '/build/index.js',
        $asset['dependencies'],
        $asset['version'],
        true
    );

    if ( file_exists( get_stylesheet_directory() . '/build/style-index.css' ) ) {
        wp_register_style(
            'mystarter-blocks',
            get_stylesheet_directory_uri() . '/build/style-index.css',
            [],
            $asset['version']
        );
    }

    if ( file_exists( get_stylesheet_directory() . '/build/index.css' ) ) {
        wp_register_style(
            'mystarter-blocks-editor',
            get_stylesheet_directory_uri() . '/build/index.css',
            [ 'wp-edit-blocks' ],
            $asset['version']
        );
    }
}
add_action( 'init', 'mystarter_register_block_assets' );

/**
 * Enqueue block editor assets.
 */
function mystarter_enqueue_block_editor_assets(): void {
    if ( wp_script_is( 'mystarter-blocks', 'registered' ) ) {
        wp_enqueue_script( 'mystarter-blocks' );
    }

    if ( wp_style_is( 'mystarter-blocks-editor', 'registered' ) ) {
        wp_enqueue_style( 'mystarter-blocks-editor' );
    }

    wp_enqueue_style(
        'mystarter-editor-sidebar',
        get_stylesheet_directory_uri() . '/assets/editor-sidebar.css',
        [],
        MYSTARTER_VERSION
    );
}
add_action( 'enqueue_block_editor_assets', 'mystarter_enqueue_block_editor_assets' );

/**
 * Enqueue front-end block assets.
 */
function mystarter_enqueue_block_assets(): void {
    if ( wp_script_is( 'mystarter-blocks', 'registered' ) ) {
        wp_enqueue_script( 'mystarter-blocks' );
    }

    if ( wp_style_is( 'mystarter-blocks', 'registered' ) ) {
        wp_enqueue_style( 'mystarter-blocks' );
    }
}
add_action( 'enqueue_block_assets', 'mystarter_enqueue_block_assets' );

/**
 * Register custom post type for news.
 */
function mystarter_register_post_types(): void {
    $labels = [
        'name'               => _x( 'Actualités', 'Post type general name', 'mystarter' ),
        'singular_name'      => _x( 'Actualité', 'Post type singular name', 'mystarter' ),
        'menu_name'          => __( 'Actualités', 'mystarter' ),
        'name_admin_bar'     => __( 'Actualité', 'mystarter' ),
        'add_new'            => __( 'Ajouter', 'mystarter' ),
        'add_new_item'       => __( 'Ajouter une actualité', 'mystarter' ),
        'new_item'           => __( 'Nouvelle actualité', 'mystarter' ),
        'edit_item'          => __( 'Modifier l’actualité', 'mystarter' ),
        'view_item'          => __( 'Voir l’actualité', 'mystarter' ),
        'all_items'          => __( 'Toutes les actualités', 'mystarter' ),
        'search_items'       => __( 'Rechercher des actualités', 'mystarter' ),
        'not_found'          => __( 'Aucune actualité trouvée.', 'mystarter' ),
        'not_found_in_trash' => __( 'Aucune actualité dans la corbeille.', 'mystarter' ),
    ];

    $args = [
        'labels'              => $labels,
        'public'              => true,
        'has_archive'         => true,
        'show_in_rest'        => true,
        'menu_icon'           => 'dashicons-megaphone',
        'supports'            => [ 'title', 'editor', 'excerpt', 'thumbnail', 'revisions' ],
        'rewrite'             => [ 'slug' => 'actualites' ],
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
    ];

    register_post_type( 'actualite', $args );
}
add_action( 'init', 'mystarter_register_post_types' );

/**
 * Register a custom block category.
 *
 * @param array $categories Existing block categories.
 *
 * @return array
 */
function mystarter_block_categories( array $categories ): array {
    $custom_category = [
        'slug'  => 'mystarter',
        'title' => __( 'MyStarter', 'mystarter' ),
        'icon'  => null,
    ];

    return array_merge( [ $custom_category ], $categories );
}
add_filter( 'block_categories_all', 'mystarter_block_categories' );

/**
 * Restrict available blocks to custom MyStarter blocks.
 *
 * @param array|bool $allowed_blocks Allowed blocks.
 * @return array
 */
function mystarter_allowed_blocks( $allowed_blocks ): array {
    unset( $allowed_blocks );

    $configured = mystarter_get_configured_blocks();

    return array_map(
        static fn( $slug ) => sprintf( 'mystarter/%s', $slug ),
        $configured['active']
    );
}
add_filter( 'allowed_block_types_all', 'mystarter_allowed_blocks' );

/**
 * Register placeholder patterns directory.
 */
function mystarter_register_block_patterns(): void {
    $pattern_dir = get_theme_file_path( 'patterns' );

    if ( ! is_dir( $pattern_dir ) ) {
        return;
    }

    register_block_pattern_category(
        'mystarter',
        [
            'label' => __( 'MyStarter', 'mystarter' ),
        ]
    );

    foreach ( glob( $pattern_dir . '/*.php' ) as $pattern_file ) {
        $pattern = include $pattern_file;

        if ( ! is_array( $pattern ) ) {
            continue;
        }

        if ( empty( $pattern['title'] ) || empty( $pattern['content'] ) ) {
            continue;
        }

        $slug = $pattern['slug'] ?? '';

        if ( ! $slug ) {
            $slug = 'mystarter/' . sanitize_title( basename( $pattern_file, '.php' ) );
        } elseif ( false === strpos( $slug, '/' ) ) {
            $slug = 'mystarter/' . sanitize_title( $slug );
        }

        unset( $pattern['slug'] );

        register_block_pattern( $slug, $pattern );
    }
}
add_action( 'init', 'mystarter_register_block_patterns', 9 );
